export const HANDLE_AUTH = "HANDLE_AUTH"
export const SAVE_CODE = "SAVE_CODE"
export const ADD_USER = "ADD_USER"
export const GET_ERROR = "GET_ERROR"
export const LOG_OUT = "LOG_OUT"
export const ADD_TOKEN = "ADD_TOKEN"
export const ADD_EMAIL = "ADD_EMAIL"